name: corner_shop_ml_env
dependencies:
  - python=3.7
  - numpy=1.21.5
  - pandas=1.3.4
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - urllib3=1.26.9
  - pip=21.2.4
  - pip:
    - seaborn==0.12.1
    - imblearn==0.0
    - python-decouple==3.6
    - SQLAlchemy==1.4.44
    - ipykernel==6.16.2